FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# IFN711

Polls is a simple API allowing consumers to view polls and vote in them.



## Suppliers [/suppliers]

### Current Suppliers [GET]

+ Response 200 (application/json)

        [
                {
                    "SupplierID": 1,
                    "Name": "Metal Supply Co",
                    "ABN": "02 999 111 888",
                    "Logo": "Legoo",
                    "CreatedAt": "2021-04-25T11:55:34Z",
                    "UpdatedAt": "2021-04-25T11:55:34Z",
                    "DeletedAt": "2021-04-25T11:55:34Z"
                },            
                {
                    "SupplierID": 2,
                    "Name": "COGS",
                    "ABN": "98 669 677 128",
                    "Logo": "Gear",
                    "CreatedAt": "2021-04-25T11:55:34Z",
                    "UpdatedAt": "2021-04-25T11:55:34Z",
                    "DeletedAt": "2021-04-25T11:55:34Z"
                },            
                {
                    "SupplierID": 3,
                    "Name": "Tools 4 days",
                    "ABN": "02 999 111 888",
                    "Logo": "Tool",
                    "CreatedAt": "2021-04-25T11:55:34Z",
                    "UpdatedAt": "2021-04-25T11:55:34Z",
                    "DeletedAt": "2021-04-25T11:55:34Z"
                },
                {
                    "SupplierID": 4,
                    "Name": "Fall ball",
                    "ABN": "12 929 121 828",
                    "Logo": "Ball",
                    "CreatedAt": "2021-04-25T11:55:34Z",
                    "UpdatedAt": "2021-04-25T11:55:34Z",
                    "DeletedAt": "2021-04-25T11:55:34Z"              
                }
            ]
            
### Create a New Supplier [POST]

+ Response 201 (application/json)

    + Headers
 
            Location: /supplier/2

    + Body

            {
                "question": "New supplier",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "supplier": "Swift",
                        "ABN": 12 222 222 333,
                        "Logo": "PHHSK"
                    }, {
                        "supplier": "Ssact",
                        "ABN": 12 999 111 333,
                        "Logo": "PHHSK"
                    }
                ]
            }

## Buyers [/buyers]

### Current Buyers [GET]

+ Response 200 (application/json)

        [
            {
                "BuyerID": 1,
                "Name": "BHP",
                "ABN": "26 125 643 045",
                "Logo": "BHP",
                "DeletedAt": "2021-04-25T11:55:34Z",
                "CreatedAt": "2021-04-25T11:55:34Z",
                "UpdatedAt": "2021-04-25T11:55:34Z"
            },            
            {
                "BuyerID": 2,
                "Name": "BMC",
                "ABN": "77 123 765 890",
                "Logo": "BMC",
                "DeletedAt": "2021-04-25T11:55:34Z",
                "CreatedAt": "2021-04-25T11:55:34Z",
                "UpdatedAt": "2021-04-25T11:55:34Z"
            },            
            {
                "BuyerID": 3,
                "Name": "BMA",
                "ABN": "58 566 908 203",
                "Logo": "BMA",
                "DeletedAt": "2021-04-25T11:55:34Z",
                "CreatedAt": "2021-04-25T11:55:34Z",
                "UpdatedAt": "2021-04-25T11:55:34Z"
            }
        ]

### Create a New Buyer [POST]

+ Response 201 (application/json)

    + Headers
 
            Location: /Buyers/2

    + Body

            {
                "question": "New Buyer",
                "published_at": "2015-08-05T08:40:51.620Z",
                "Name": "smashers",
                "ABN": "61 882 999 855",
                "Logo": "pem.png"
            }

 
 
## Tenders [/tenders]

### Current Tenders [GET]

+ Response 200 (application/json)

        [
          {
              "TenderID": 1,
              "BuyerID": 1,
              "PublishedAt": "2021-04-25T11:55:34Z",
              "ClosingAt": "2021-04-25T11:55:34Z",
              "Description": "Create metal sheets",
              "State_ID": 1,
              "City_ID": 2,
              "Offer": 6000.00,
              "DeletedAt":"2021-04-25T11:55:34Z" ,
              "CreatedAt": "2021-04-25T11:55:34Z", 
              "UpdatedAt": "Monday"
          },
          {
              "TenderID": 2,
              "BuyerID": 2,
              "PublishedAt": "2021-04-25T11:55:34Z",
              "ClosingAt": "2021-04-25T11:55:34Z",
              "Description": "Create metal sheets",
              "State_ID": 2,
              "City_ID": 1,
              "Offer": 6000.00,
              "DeletedAt": "2021-04-25T11:55:34Z",
              "CreatedAt": "2021-04-25T11:55:34Z", 
              "UpdatedAt": "Tuesday"
          },                
          {
              "TenderID": 3,
              "BuyerID": 2,
              "PublishedAt": "2021-04-25T11:55:34Z",
              "ClosingAt": "2021-04-25T11:55:34Z",
              "Description": "Create metal sheets",
              "State_ID": 2,
              "City_ID": 3,
              "Offer": 6000.00,
              "DeletedAt": "2021-04-25T11:55:34Z",
              "CreatedAt": "2021-04-25T11:55:34Z", 
              "UpdatedAt": "Friday"
          },                                
          {
              "TenderID": 4,
              "BuyerID": 3,
              "PublishedAt": "2021-04-25T11:55:34Z",
              "ClosingAt": "2021-04-25T11:55:34Z",
              "Description": "Create metal sheets",
              "State_ID": 3,
              "City_ID": 4,
              "Offer": 6000.00,
              "DeletedAt": "2021-04-25T11:55:34Z",
              "CreatedAt": "2021-04-25T11:55:34Z", 
              "UpdatedAt": "Wednesday"
          }]

### Add tender [POST]

+ Response 201 (application/json)

    + Headers
 
            Location: /tenders/2

    + Body

            {
                "Question": "Add tender",
                "PublishedAt": "2015-08-05T08:40:51.620Z",
                "Tender_ID": 1,
                "Buyer_ID": 2,
                "Description": "Beat metal",
                "State_ID": 4,
                "City_ID": 3,
                "Offer": 5000.00
            }
            

## Profile [/profile]

### Current Profiles [GET]

+ Response 200 (application/json)

        {
            "UserID": 1,
            "Name": "BHP",
            "Email": "bhp@test.com",
            "Password": "BHP1234",
            "BuyerID": 1,
            "SupplierID": null,
            "DeletedAt": "2021-04-25T11:55:34Z",
            "CreatedAt": "2021-04-25T11:55:34Z",
            "UpdatedAt": "2021-04-25T11:55:34Z",
            "Token": "Asi120Ke",
            "RefreshToken": "asdasaccAE"
        }

## Proposals [/proposals]

### Currents Proposals [GET]

+ Response 200 (application/json)

                [
                  {
                      "PropsalID": 1,
                      "TenderID": 1,
                      "SupplierID": 1,
                      "Description": "Make the sheet metal",
                      "ApprovedAt": "2021-04-25T11:55:34Z",
                      "Offer": 5500.00,
                      "CreatedAt": "2021-04-25T11:55:34Z",
                      "UpdatedAt": "2021-04-25T11:55:34Z",
                      "DeletedAt": "2021-04-25T11:55:34Z"
                  },
                  {
                      "PropsalID": 2,
                      "TenderID": 1,
                      "SupplierID": 2,
                      "Description": "Mould sheet metal",
                      "ApprovedAt": "2021-04-25T11:55:34Z",
                      "Offer": 5459.00,
                      "CreatedAt": "2021-04-25T11:55:34Z",
                      "UpdatedAt": "2021-04-25T11:55:34Z",
                      "DeletedAt": "2021-04-25T11:55:34Z"
                  }, 
                  {
                      "PropsalID": 3,
                      "TenderID": 1,
                      "SupplierID": 4,
                      "Description": "Beat sheet metal",
                      "ApprovedAt": "2021-04-25T11:55:34Z",
                      "Offer": 5230.00,
                      "CreatedAt": "2021-04-25T11:55:34Z",
                      "UpdatedAt": "2021-04-25T11:55:34Z",
                      "DeletedAt": "2021-04-25T11:55:34Z"
                  },        
                  {
                      "PropsalID": 4,
                      "TenderID": 2,
                      "SupplierID": 1,
                      "Description": "Modify truck",
                      "ApprovedAt": "2021-04-25T11:55:34Z",
                      "Offer": 5500.00,
                      "CreatedAt": "2021-04-25T11:55:34Z",
                      "UpdatedAt": "2021-04-25T11:55:34Z",
                      "DeletedAt": "2021-04-25T11:55:34Z"
                  }
                ]
                
### Add proposal [POST]

+ Request (application/json)

        {
            "proposal": "What is your proposal?",
            "proposalID": [
                1, 2, 3, 4, 5
            ],
            "tenderID": [
                1,2,3,4,5
            ], 
            "supplierID": [
             1,2,3,4,5,6,7,8
            ],
            "offer": 213.2
        }

+ Response 201 (application/json)

    + Headers
 
            Location: /proposals/2

    + Body

            {
                "question": "What is your proposal?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "proposalID": 1,
                "tenderID": 1,
                "supplierID": 2,
                "offer": 6656.00
            }
